apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask-deployment
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: rakhemanohar/flask:1.1
        ports:
        - containerPort: 5000
