apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30009
    targetPort: 5000
